plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - changelogFile: docs/CHANGELOG.md
  - "@semantic-release/npm"
  - - "@semantic-release/git"
    - assets: ["docs", "package.json"]
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
preset: conventionalcommits
branches:
  - main
