version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/repo
  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: ~/repo
      paths: .

executors:
  daneel:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

jobs:
  build:
    executor: daneel
    steps:
      - *attach_workspace
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
      - codecov/upload:
          file: coverage/*.json
      - *persist_to_workspace
  publish:
    executor: daneel
    steps:
      - *attach_workspace
      - checkout
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - publish:
          context: pi
          requires:
            - build
          filters:
            branches:
              only: master
